### ISSUE TITLE
Hay una lista de comandos para hacer guiones y titulos?

### ISSUE THREAD

**Issue by Celia-Vinagre-Izquierdo** [Celia-Vinagre-Izquierdo/cvinagre-csic-github#1]

**Comment by jmoldon** [comment]
No sé si has encontrado lo que buscabas. Si te refieres a resumen de la sintaxis markdown tienes la oficial https://www.markdownguide.org/cheat-sheet/
aunque ésta es más útil porque sale el ejemplo y el resultado final: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

Ánimos!
